#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CMD="${0##*/}"
# Locate script
BASE=$(readlink -f $0)
BASE=${BASE%/*}

export CLUSTER_ADM_BASE=${BASE}

# Source config file if it exists for extra settings
SLURM_MUX_CONF=${CLUSTER_ADM_BASE}/etc/slurm_mux.conf
if [[ -r ${SLURM_MUX_CONF} ]]; then
	source ${SLURM_MUX_CONF}
fi

# Setup logging if configured and directory exists
LOGFILE="/dev/null"
if [[ -d ${SLURM_MUX_LOG_DIR} && ${SLURM_MUX_ENABLE_LOG} == "yes" ]]; then
	LOGFILE="${SLURM_MUX_LOG_DIR}/${CMD}-${SLURM_SCRIPT_CONTEXT}-job-${SLURMD_NODENAME}-$(hostname).log"
	exec >>${LOGFILE} 2>&1
fi

# Global scriptlets
for SCRIPTLET in ${BASE}/${SLURM_SCRIPT_CONTEXT}.d/*.${SLURM_SCRIPT_CONTEXT}; do
	if [[ -x ${SCRIPTLET} ]]; then
		echo "Running ${SCRIPTLET}"
		${SCRIPTLET} $@ >>${LOGFILE} 2>&1
	fi
done

# Per partition scriptlets
for SCRIPTLET in ${BASE}/partition-${SLURM_JOB_PARTITION}-${SLURM_SCRIPT_CONTEXT}.d/*.${SLURM_SCRIPT_CONTEXT}; do
	if [[ -x ${SCRIPTLET} ]]; then
		echo "Running ${SCRIPTLET}"
		${SCRIPTLET} $@ >>${LOGFILE} 2>&1
	fi
done
