#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JOBSUDOERFILE="/var/slurm-sudoers.d/${SLURM_JOB_USER}-${SLURM_JOB_ID}"

if [[ ${SLURM_SCRIPT_CONTEXT} == "prolog_slurmd" &&
	-n "${SLURM_JOB_USER}" &&
	-n "${SLURM_JOB_ID}" &&
	-d /var/slurm-sudoers.d ]]; then
	(
		umask 117
		echo "${SLURM_JOB_USER} ALL=(ALL) NOPASSWD: ALL" >${JOBSUDOERFILE}
	)
elif [[ ${SLURM_SCRIPT_CONTEXT} == "epilog_slurmd" &&
	-n "${SLURM_JOB_USER}" &&
	-n "${SLURM_JOB_ID}" &&
	-e "${JOBSUDOERFILE}" ]]; then
	rm -f "${JOBSUDOERFILE}"
fi
